#!/usr/bin/env Rscript
# Standalone script to plot ASMR data from the *downloaded* (non-imputed) CSV
# Expects: outputs/weekly_asmr_from_download.csv (generated by your download-based ASMR script)

suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(scales)
  library(ggplot2)
  library(ISOweek)
})

# -------------------------------------------------------------------
# CONFIG
# -------------------------------------------------------------------
SUFFIX <- "from_download"
asmr_csv <- Sys.getenv("ASMR_CSV", unset = "outputs/weekly_asmr_from_download.csv")

# -------------------------------------------------------------------
# Utilities
# -------------------------------------------------------------------
iso_week_to_monday <- function(y, w) {
  # True ISO week Monday (YYYY-Www-1)
  ISOweek::ISOweek2date(sprintf("%04d-W%02d-1", as.integer(y), as.integer(w)))
}

# -------------------------------------------------------------------
# Advanced interactive plot option
# -------------------------------------------------------------------
create_interactive_asmr_plot <- function() {
  if (!requireNamespace("plotly", quietly = TRUE)) {
    cat("Installing plotly for interactive plots...\n")
    install.packages("plotly")
  }
  library(plotly)

  asmr_data <- read.csv(asmr_csv, stringsAsFactors = FALSE) %>%
    mutate(
      week_start = iso_week_to_monday(year, week),
      week_label = paste0(year, "-W", sprintf("%02d", week))
    )

  p <- plot_ly(asmr_data, x = ~week_start) %>%
    add_trace(y = ~asmr_unvaccinated,
              name = 'Unvaccinated',
              type = 'scatter', mode = 'lines+markers',
              line = list(color = '#D55E00', width = 2),
              marker = list(size = 4),
              text = ~paste("Week:", week_label, "<br>ASMR:", round(asmr_unvaccinated, 2)),
              hoverinfo = 'text') %>%
    add_trace(y = ~asmr_vaccinated,
              name = 'Vaccinated',
              type = 'scatter', mode = 'lines+markers',
              line = list(color = '#0072B2', width = 2, dash = 'dash'),
              marker = list(size = 4),
              text = ~paste("Week:", week_label, "<br>ASMR:", round(asmr_vaccinated, 2)),
              hoverinfo = 'text') %>%
    add_trace(y = ~asmr_total,
              name = 'Total Population',
              type = 'scatter', mode = 'lines+markers',
              line = list(color = '#009E73', width = 2, dash = 'dot'),
              marker = list(size = 4),
              text = ~paste("Week:", week_label, "<br>ASMR:", round(asmr_total, 2)),
              hoverinfo = 'text') %>%
    layout(title = list(text = "Weekly ASMR by Vaccination Status - Non-Imputed",
                        font = list(size = 18)),
           xaxis = list(title = "Date", rangeslider = list(visible = TRUE), type = "date"),
           yaxis = list(title = "ASMR per 100,000 person-years"),
           hovermode = 'closest',
           legend = list(x = 0.02, y = 0.98))

  htmlwidgets::saveWidget(
    p,
    sprintf("outputs/weekly_asmr_interactive_%s.html", SUFFIX),
    selfcontained = TRUE,
    title = "Weekly ASMR Analysis (Non-Imputed)"
  )
  cat(sprintf("Interactive plot saved to outputs/weekly_asmr_interactive_%s.html\n", SUFFIX))
  p
}

# -------------------------------------------------------------------
# Heatmap
# -------------------------------------------------------------------
create_asmr_heatmap <- function() {
  asmr_data <- read.csv(asmr_csv, stringsAsFactors = FALSE) %>%
    mutate(
      rate_ratio = ifelse(asmr_vaccinated > 0, asmr_unvaccinated / asmr_vaccinated, NA_real_),
      rate_ratio_capped = pmin(rate_ratio, 10, na.rm = TRUE)
    )

  heatmap_data <- asmr_data %>%
    select(year, week, asmr_unvaccinated, asmr_vaccinated, asmr_total, rate_ratio_capped) %>%
    pivot_longer(
      cols = c(asmr_unvaccinated, asmr_vaccinated, asmr_total, rate_ratio_capped),
      names_to = "metric", values_to = "value"
    ) %>%
    mutate(
      metric = case_when(
        metric == "asmr_unvaccinated" ~ "Unvaccinated ASMR",
        metric == "asmr_vaccinated"   ~ "Vaccinated ASMR",
        metric == "asmr_total"         ~ "Total ASMR",
        metric == "rate_ratio_capped"  ~ "Rate Ratio (Unvax/Vax)",
        TRUE ~ metric
      )
    )

  p <- ggplot(heatmap_data, aes(x = week, y = factor(year), fill = value)) +
    geom_tile(color = "white", size = 0.1) +
    facet_wrap(~metric, scales = "free", ncol = 2) +
    scale_fill_gradientn(
      colors = c("navy", "blue", "cyan", "yellow", "orange", "red"),
      name = "Value", na.value = "gray90"
    ) +
    scale_x_continuous(breaks = seq(0, 52, 4), expand = c(0, 0)) +
    labs(
      title = "Weekly ASMR Heatmap - Non-Imputed",
      subtitle = "ESP 2013 standardized; <15 excluded; unknown YOB excluded",
      x = "Week of Year", y = "Year"
    ) +
    theme_minimal(base_size = 11) +
    theme(legend.position = "bottom", panel.spacing = unit(1, "lines"))

  ggsave(sprintf("outputs/weekly_asmr_heatmap_%s.png", SUFFIX),
         plot = p, width = 14, height = 10, dpi = 300, bg = "white")
  cat(sprintf("Heatmap saved to outputs/weekly_asmr_heatmap_%s.png\n", SUFFIX))
  p
}

# -------------------------------------------------------------------
# Cumulative plot
# -------------------------------------------------------------------
create_cumulative_plot <- function() {
  asmr_data <- read.csv(asmr_csv, stringsAsFactors = FALSE) %>%
    mutate(week_start = iso_week_to_monday(year, week)) %>%
    arrange(year, week) %>%
    mutate(
      cumulative_unvaccinated = cumsum(asmr_unvaccinated),
      cumulative_vaccinated   = cumsum(asmr_vaccinated),
      cumulative_total        = cumsum(asmr_total)
    ) %>%
    pivot_longer(
      cols = starts_with("cumulative"),
      names_to = "group", values_to = "cumulative_asmr",
      names_prefix = "cumulative_"
    ) %>%
    mutate(group = str_to_title(group))

  p <- ggplot(asmr_data, aes(x = week_start, y = cumulative_asmr, color = group)) +
    geom_line(size = 1.5, alpha = 0.8) +
    geom_area(aes(fill = group), alpha = 0.2) +
    scale_color_manual(values = c("Unvaccinated"="#D55E00","Vaccinated"="#0072B2","Total"="#009E73")) +
    scale_fill_manual(values = c("Unvaccinated"="#D55E00","Vaccinated"="#0072B2","Total"="#009E73"), guide = "none") +
    scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") +
    scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.05))) +
    labs(
      title = "Cumulative ASMR - Non-Imputed",
      subtitle = "Running sum of weekly ASMR per 100,000 person-years",
      x = "Date", y = "Cumulative ASMR"
    ) +
    theme_minimal(base_size = 12) +
    theme(legend.position = "top", axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave(sprintf("outputs/weekly_asmr_cumulative_%s.png", SUFFIX),
         plot = p, width = 12, height = 7, dpi = 300, bg = "white")
  cat(sprintf("Cumulative plot saved to outputs/weekly_asmr_cumulative_%s.png\n", SUFFIX))
  p
}

# -------------------------------------------------------------------
# Rate ratio plot
# -------------------------------------------------------------------
create_rate_ratio_plot <- function() {
  asmr_data <- read.csv(asmr_csv, stringsAsFactors = FALSE) %>%
    mutate(
      week_start = iso_week_to_monday(year, week),
      rate_ratio = ifelse(asmr_vaccinated > 0, asmr_unvaccinated / asmr_vaccinated, NA_real_),
      rate_ratio_smooth = zoo::rollmean(rate_ratio, k = 4, fill = NA, align = "center")
    ) %>% filter(!is.na(rate_ratio))

  p <- ggplot(asmr_data, aes(x = week_start)) +
    geom_hline(yintercept = 1, linetype = "dashed", color = "gray50", size = 1) +
    annotate("rect", xmin = min(asmr_data$week_start), xmax = max(asmr_data$week_start),
             ymin = 0, ymax = 1, alpha = 0.1, fill = "blue") +
    annotate("rect", xmin = min(asmr_data$week_start), xmax = max(asmr_data$week_start),
             ymin = 1, ymax = max(asmr_data$rate_ratio, na.rm = TRUE),
             alpha = 0.1, fill = "red") +
    geom_point(aes(y = rate_ratio), color = "gray40", alpha = 0.5, size = 1) +
    geom_line(aes(y = rate_ratio), color = "gray40", alpha = 0.3) +
    geom_line(aes(y = rate_ratio_smooth), color = "darkred", size = 1.5) +
    scale_y_continuous(trans = "log10",
                       breaks = c(0.5, 1, 2, 5, 10, 20),
                       labels = function(x) format(x, scientific = FALSE)) +
    scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") +
    labs(
      title = "Mortality Rate Ratio (Unvax/Vax) - Non-Imputed",
      subtitle = "Values > 1 = higher mortality in unvaccinated (log scale)",
      x = "Date", y = "Rate Ratio",
      caption = "Gray points: weekly | Dark red: 4-week moving average"
    ) +
    theme_minimal(base_size = 12) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave(sprintf("outputs/weekly_asmr_rate_ratio_%s.png", SUFFIX),
         plot = p, width = 12, height = 7, dpi = 300, bg = "white")
  cat(sprintf("Rate ratio plot saved to outputs/weekly_asmr_rate_ratio_%s.png\n", SUFFIX))
  p
}

# -------------------------------------------------------------------
# Main ASMR line plot
# -------------------------------------------------------------------
create_main_asmr_plot <- function() {
  asmr_data <- read.csv(asmr_csv, stringsAsFactors = FALSE) %>%
    mutate(week_start = iso_week_to_monday(year, week)) %>%
    pivot_longer(
      cols = c(asmr_unvaccinated, asmr_vaccinated, asmr_total),
      names_to = "group", values_to = "asmr"
    ) %>%
    mutate(group = recode(group,
                          "asmr_unvaccinated" = "Unvaccinated",
                          "asmr_vaccinated"   = "Vaccinated",
                          "asmr_total"        = "Total Population"))

  peak_unvax <- asmr_data %>% filter(group == "Unvaccinated") %>% slice_max(asmr, n = 1)
  peak_vax   <- asmr_data %>% filter(group == "Vaccinated")   %>% slice_max(asmr, n = 1)

  p <- ggplot(asmr_data, aes(x = week_start, y = asmr, color = group, group = group)) +
    theme_minimal(base_size = 12) +
    geom_line(aes(linetype = group), size = 1.2, alpha = 0.9) +
    geom_point(size = 0.8, alpha = 0.5) +
    geom_smooth(aes(fill = group), method = "loess", span = 0.2,
                alpha = 0.1, size = 0.5, linetype = "dotted", se = TRUE) +
    scale_color_manual(values = c("Unvaccinated"="#D55E00","Vaccinated"="#0072B2","Total Population"="#009E73"),
                       name = "Population Group") +
    scale_fill_manual(values = c("Unvaccinated"="#D55E00","Vaccinated"="#0072B2","Total Population"="#009E73"),
                      guide = "none") +
    scale_linetype_manual(values = c("Unvaccinated"="solid","Vaccinated"="dashed","Total Population"="dotted"),
                          name = "Population Group") +
    scale_y_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE),
                       expand = expansion(mult = c(0.05, 0.1))) +
    scale_x_date(date_breaks = "3 months", date_labels = "%b %Y",
                 expand = expansion(mult = c(0.02, 0.02))) +
    labs(
      title = "Weekly ASMR by Vaccination Status - Non-Imputed",
      subtitle = "Per 100,000 person-years - ESP 2013 standardized - <15 excluded - unknown YOB excluded",
      x = "Date", y = "ASMR per 100,000 person-years",
      caption = paste(
        "Data source: MZCR (downloaded version) | Analysis span:",
        paste0(min(asmr_data$year), "-W", sprintf("%02d", min(asmr_data$week[asmr_data$year == min(asmr_data$year)]))),
        "to",
        paste0(max(asmr_data$year), "-W", sprintf("%02d", max(asmr_data$week[asmr_data$year == max(asmr_data$year)])))
      )
    ) +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 12, hjust = 0.5, color = "gray40"),
      axis.text.x = element_text(angle = 45, hjust = 1),
      legend.position = "top"
    )

  if (nrow(peak_unvax) > 0 && nrow(peak_vax) > 0) {
    p <- p +
      annotate("text",
               x = peak_unvax$week_start[1],
               y = peak_unvax$asmr[1] * 1.05,
               label = paste("Peak unvaccinated:\n", round(peak_unvax$asmr[1], 1)),
               size = 3, color = "#D55E00", fontface = "bold") +
      annotate("text",
               x = peak_vax$week_start[1],
               y = peak_vax$asmr[1] * 1.05,
               label = paste("Peak vaccinated:\n", round(peak_vax$asmr[1], 1)),
               size = 3, color = "#0072B2", fontface = "bold")
  }

  p
}

# -------------------------------------------------------------------
# Main execution
# -------------------------------------------------------------------
cat("\n", strrep("=", 60), "\n", sep = "")
cat("ASMR VISUALIZATION SCRIPT (NON-IMPUTED)\n")
cat(strrep("=", 60), "\n\n", sep = "")

if (!file.exists(asmr_csv)) {
  stop(sprintf("Error: %s not found. Generate it with the download-based ASMR script first.", asmr_csv))
}
if (!dir.exists("outputs")) dir.create("outputs", recursive = TRUE)

cat("Generating standard ASMR plot...\n")
main_plot <- create_main_asmr_plot()

ggsave(sprintf("outputs/weekly_asmr_plot_%s.png", SUFFIX),
       plot = main_plot, width = 14, height = 8, dpi = 300, bg = "white")
ggsave(sprintf("outputs/weekly_asmr_plot_%s.pdf", SUFFIX),
       plot = main_plot, width = 14, height = 8, device = "pdf")

cat(sprintf("Main ASMR plot saved to outputs/weekly_asmr_plot_%s.png and .pdf\n", SUFFIX))

cat("\nGenerating additional visualizations...\n")
heatmap_plot    <- create_asmr_heatmap()
cumulative_plot <- create_cumulative_plot()
rate_ratio_plot <- create_rate_ratio_plot()

# Interactive (optional)
tryCatch({
  interactive_plot <- create_interactive_asmr_plot()
}, error = function(e) {
  cat("Note: Could not create interactive plot. Install 'plotly' if needed.\n")
})

# -------------------------------------------------------------------
# Summary stats
# -------------------------------------------------------------------
cat("\n", strrep("=", 60), "\n", sep = "")
cat("DETAILED ASMR ANALYSIS (NON-IMPUTED)\n")
cat(strrep("=", 60), "\n\n", sep = "")

asmr_data <- read.csv(asmr_csv, stringsAsFactors = FALSE)

cat("Overall Statistics:\n", strrep("-", 40), "\n", sep = "")
summary_stats <- asmr_data %>%
  summarise(
    across(c(asmr_unvaccinated, asmr_vaccinated, asmr_total),
           list(
             Mean   = ~mean(., na.rm = TRUE),
             Median = ~median(., na.rm = TRUE),
             Min    = ~min(., na.rm = TRUE),
             Max    = ~max(., na.rm = TRUE),
             SD     = ~sd(., na.rm = TRUE),
             IQR    = ~IQR(., na.rm = TRUE)
           ), .names = "{.fn}_{.col}")
  ) %>%
  pivot_longer(everything(),
               names_to = c("Statistic", "Group"),
               names_pattern = "(.*)_asmr_(.*)") %>%
  pivot_wider(names_from = Group, values_from = value) %>%
  mutate(across(where(is.numeric), ~round(., 2)))
print(summary_stats, row.names = FALSE)

cat("\n\nYearly Average ASMR:\n", strrep("-", 40), "\n", sep = "")
yearly_stats <- asmr_data %>%
  group_by(year) %>%
  summarise(
    Unvaccinated = round(mean(asmr_unvaccinated, na.rm = TRUE), 2),
    Vaccinated   = round(mean(asmr_vaccinated,   na.rm = TRUE), 2),
    Total        = round(mean(asmr_total,        na.rm = TRUE), 2),
    `Avg Rate Ratio` = round(mean(asmr_unvaccinated / asmr_vaccinated, na.rm = TRUE), 2)
  )
print(yearly_stats, row.names = FALSE)

cat("\n\nPeak Mortality Weeks:\n", strrep("-", 40), "\n", sep = "")
peak_unvax <- asmr_data %>% slice_max(asmr_unvaccinated, n = 1) %>%
  mutate(Group = "Unvaccinated", Peak_ASMR = round(asmr_unvaccinated, 2)) %>%
  select(Group, year, week, Peak_ASMR)
peak_vax <- asmr_data %>% slice_max(asmr_vaccinated, n = 1) %>%
  mutate(Group = "Vaccinated", Peak_ASMR = round(asmr_vaccinated, 2)) %>%
  select(Group, year, week, Peak_ASMR)
peak_total <- asmr_data %>% slice_max(asmr_total, n = 1) %>%
  mutate(Group = "Total", Peak_ASMR = round(asmr_total, 2)) %>%
  select(Group, year, week, Peak_ASMR)
peak_weeks <- bind_rows(peak_unvax, peak_vax, peak_total)
print(peak_weeks, row.names = FALSE)

cat("\n", strrep("=", 60), "\n", "All visualizations completed successfully!\n", strrep("=", 60), "\n", sep = "")
